---
version: 2

# registries:
#  spacelift:
#    type: terraform-registry
#    url: https://app.spacelift.io
#    token: ${{ secrets.SPACELIFT_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    # registries:
    #   - spacelift
    schedule:
      interval: "daily"
