name: "tfsec"
description: "Run the tfsec by Aquasec (static code analysis tool) on the project to identify Terraform security issues."

author: "letsrockthefuture"

inputs:
  working_directory:
    description: "The working directory of the Terraform project."
    type: string
    required: true

  github_token:
    description: "The GitHub API token."
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: "Run Checkout by GitHub Actions"
      uses: letsrockthefuture/reusable-workflows/templates/checkout@main

    - name: "Run tfsec by Aquasec"
      uses: tfsec/tfsec-sarif-action@v0.0.6
      with:
        working_directory: ${{ input.working_directory }}
        sarif_file: "tfsec.sarif"
        github_token: ${{ inputs.tfsec_token }}

    - name: "Upload SARIF result to the security code scanning alerts"
      uses: letsrockthefuture/reusable-workflows/templates/codeql/upload-sarif@main
      with:
        sarif_file: "tfsec.sarif"

    - name: "tfsec PR commenter"
      uses: tfsec/tfsec-pr-commenter-action@main
      if: github.event_name == 'pull_request'
      with:
        github_token: ${{ inputs.tfsec_token }}
