name: "tfsec"
description: "Run the tfsec by Aquasec (static code analysis tool) on the project to identify Terraform security issues."

author: "letsrockthefuture"

inputs:
  cli_config_credentials_token:
    description: "The Terraform Cloud API token."
    type: string
    required: true

  working_directory:
    description: "The working directory of the Terraform project."
    type: string
    default: .
    required: false

  tfsec_token:
    description: "The GitHub API token."
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - uses: aquasec/tfsec-ci:latest

    - name: "Run tfsec by Aquasec"
      
        sarif_file: "tfsec.sarif"

    - name: "Upload SARIF result to the security code scanning alerts"
      uses: letsrockthefuture/reusable-workflows/templates/codeql/upload-sarif@main
      with:
        sarif_file: "tfsec.sarif"

    - name: "tfsec PR commenter"
      uses: tfsec/tfsec-pr-commenter-action@v0.1.10
      if: github.event_name == 'pull_request'
      with:
        github_token: ${{ inputs.tfsec_token }}
