name: "Checkov"
description: "Run the Checkov by bridgecrew.io (static code analysis tool) on the project to identify Terraform security issues."

author: "letsrockthefuture"

# inputs:
#   bc_api_key:
#     description: "The API key for bridgecrew.io"
#     type: string
#     required: true

  # working_directory:
  #   description: "The working directory to run Terraform in."
  #   type: string
  #   default: .
  #   required: true

  # github_repository:
  #   description: "The GitHub repository to scan."
  #   type: string
  #   required: true

  # github_ref:
  #   description: "The GitHub Ref."
  #   type: string
  #   required: true

  # github_sha:
  #   description: "The GitHub SHA."
  #   type: string
  #   required: true

  # github_server_url:
  #   description: "The GitHub server URL."
  #   type: string
  #   required: true

runs:
  using: "composite"
  steps:
    - uses: "docker://bridgecrew/checkov:2.0.701"
      args:
        - --version
