name: "Checkov"
description: "Run the Checkov by bridgecrew.io (static code analysis tool) on the project to identify Terraform security issues."

author: "letsrockthefuture"

inputs:
  bc_api_key:
    description: "The API key for bridgecrew.io"
    type: string
    required: true

  # working_directory:
  #   description: "The working directory to run Terraform in."
  #   type: string
  #   default: .
  #   required: true

  github_repository:
    description: "The GitHub repository to scan."
    type: string
    default: ${{ github.repository }}
    required: false

  github_ref:
    description: "The GitHub Ref."
    type: string
    default: ${{ github.ref }}
    required: false

  github_sha:
    description: "The GitHub SHA."
    type: string
    default: ${{ github.sha }}
    required: false

  github_server_url:
    description: "The GitHub server URL."
    type: string
    default: $GITHUB_SERVER_URL
    required: false

runs:
  using: "composite"
  steps:
    - name: "Run Checkov by bridgecrew.io"
      uses: bridgecrewio/bridgecrew-action@master
      with:
        api-key: ${{ inputs.bc_api_key }}
        # directory: ${{ inputs.working_directory }}
        soft_fail: true # false
        skip_check: CKV_GIT_1,CKV_SECRET_6
        output_format: "sarif"
        quiet: true
        # download_external_modules: true
      env:
        GITHUB_REPOSITORY: ${{ inputs.github_repository }}
        GITHUB_REF: ${{ inputs.github_ref }}
        GITHUB_SHA: ${{ inputs.github_sha }}
        GITHUB_SERVER_URL: ${{ inputs.github_server_url }}

    - name: Echo env
      run: |
        echo $GITHUB_REPOSITORY
        echo $GITHUB_REF
        echo $GITHUB_SHA
        echo $GITHUB_SERVER_URL

    - name: "Upload SARIF result to the security code scanning alerts"
      uses: letsrockthefuture/reusable-workflows/templates/codeql/upload-sarif@main
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      with:
        sarif_file: "results.sarif"
