name: "Static code analysis"
description: "Run the Checkov by bridgecrew.io (static code analysis tool) on the project to identify Terraform security issues."

runs:
  using: "composite"
  steps:
    - name: "Run Checkout by GitHub Actions"
      uses: letsrockthefuture/reusable-workflows/templates/checkout@main

    - name: "Run Checkov by bridgecrew.io"
      uses: bridgecrewio/checkov-action@master
      with:
        framework: "terraform"
        directory: "terraform"
        skip_check: CKV_GIT_1
