name: "Checkov"
description: "Run the Checkov by bridgecrew.io (static code analysis tool) on the project to identify Terraform security issues."

author: "letsrockthefuture"

inputs:
  bc_api_key:
    description: "The API key for bridgecrew.io"
    type: string
    required: true
  github_repository:
    description: "The GitHub repository to scan."
    type: string
    required: true
  github_ref:
    description: "The GitHub Ref."
    type: string
    required: true
  github_sha:
    description: "The GitHub SHA."
    type: string
    required: true
  github_server_url:
    description: "The GitHub server URL."
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: "Run Checkout by GitHub Actions"
      uses: letsrockthefuture/reusable-workflows/templates/checkout@main

    - name: "Run Checkov by bridgecrew.io"
      uses: bridgecrewio/bridgecrew-action@master
      with:
        api-key: ${{ inputs.bc_api_key }}
        directory: "terraform"
        soft_fail: true
        # skip_check: CKV_GIT_1,CKV_SECRET_6
        output_format: "sarif"
        download_external_modules: true
      env:
        GITHUB_REPOSITORY: ${{ inputs.github_repository }}
        GITHUB_REF: ${{ inputs.github_ref }}
        GITHUB_SHA: ${{ inputs.github_sha }}
        GITHUB_SERVER_URL: ${{ inputs.github_server_url }}

    - name: "Expose the SARIF Checkov results"
      uses: actions/upload-artifact@v2
      with:
        name: "Checkov SARIF results"
        path: "results.sarif"

    - name: "Upload SARIF result to the security code scanning alerts"
      uses: letsrockthefuture/reusable-workflows/templates/codeql/upload-sarif@main
      with:
        sarif_file: "results.sarif"
