name: "Static code analysis"
description: "Run the static code analysis tool called Checkov (by bridgecrew.io) on the project to identify Terraform security issues."

runs:
  using: "composite"
  steps:
    - name: Checkout
    - uses: letsrockthefuture/reusable-workflows/templates/checkout/workflow.yaml@main

    - name: "Run Checkov by bridgecrew.io"
      uses: bridgecrewio/checkov-action@master
      with:
        framework: "terraform"
        directory: "terraform"
        skip_check: CKV_GIT_1
