name: Static code analysis

on:
  workflow_call:

jobs:
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - name: "Run Checkov by bridgecrew.io"
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: terraform
          directory: terraform
          skip_check: CKV_GIT_1