name: "Terraform planning"
description: "Run the Terraform `terraform plan*` command on project."

author: "letsrockthefuture"

runs:
  using: "composite"
  steps:
    - name: "Plan"
      shell: bash
      run: |
        @terraform fmt -recursive -check -diff
	      @terraform init
        @terraform get
        @terraform validate -no-color
        @terraform plan -no-color

    - name: "Plan status"
      if: steps.terraform_plan.outcome == 'failure'
      shell: bash
      run: |
        exit 1
