name: "Terraform planning"
description: "Run the Terraform `terraform plan` command on project."

runs:
  using: "composite"
  steps:
    - name: "Run `checkout` by GitHub Actions™"
      uses: letsrockthefuture/reusable-workflows/templates/checkout@main

    - name: "Plan"
      shell: bash
      run: |
        make init
        make terraform/plan

    - name: "Plan status"
      if: steps.terraform_plan.outcome == 'failure'
      shell: bash
      run: |
        exit 1
