name: "Terraform planning"
description: "Run the Terraform `terraform plan` command on project."

author: "letsrockthefuture"

inputs:
  working_directory:
    description: "The working directory to run Terraform in."
    type: string
    default: .
    required: true

defaults:
  run:
    working-directory: "${{ inputs.working_directory }}"

runs:
  using: "composite"
  steps:
    - name: "Plan"
      id: "terraform_plan"
      shell: bash
      run: |
        terraform fmt -recursive -check -diff
        terraform init
        terraform get
        terraform validate -no-color
        terraform plan -no-color

    - name: "Plan status"
      if: steps.terraform_plan.outcome == 'failure'
      shell: bash
      run: |
        exit 1
