name: "Terraform planning"
description: "Run the Terraform plan command on project."

runs:
  using: "composite"
  steps:
    - name: "Plan"
      shell: bash
      run: |
        make init
        make terraform/plan

    - name: "Plan status"
      if: steps.terraform_plan.outcome == 'failure'
      shell: bash
      run: |
        exit 1
