name: "Terraform initializing"
description: "Run the Terraform `terraform init` command on project."

author: "letsrockthefuture"

runs:
  using: "composite"
  steps:
    - name: "Init"
      shell: bash
      run: |
        make init
        make terraform/init
