name: "Terraform initializing"
description: "Run the Terraform `terraform init` command on project."

author: "letsrockthefuture"

inputs:
  working_directory:
    description: "The working directory of the Terraform project."
    type: string
    default: .
    required: false

runs:
  using: "composite"
  steps:
    - name: "Init"
      shell: bash
      env:
        CHDIR: ${{ inputs.working_directory }}
      run: |
        make init
        make terraform/init
