name: "Terraform applying"
description: "Run the Terraform `terraform apply*` command on project."

author: "letsrockthefuture"

runs:
  using: "composite"
  steps:
    - name: "Apply"
      shell: bash
      run: |
        @terraform init
        @terraform get
        @terraform apply -auto-approve
