name: "Golang security checker"
description: "Inspects source code for security problems by scanning the Go AST."

# inputs:

runs:
  using: "composite"
  steps:
    - name: "Run `checkout` by GitHub Actions™"
      uses: letsrockthefuture/reusable-workflows/templates/checkout@main

    - name: "Run gosec by Secure Go"
      uses: securego/gosec@master
      with:
        args: "-no-fail -fmt sarif -out results.sarif ./..."

    - name: "Upload SARIF result file to GitHub"
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
