name: "Golang security checker"
description: "Inspects source code for security problems by scanning the Go AST."

author: "letsrockthefuture"

# inputs:

runs:
  using: "composite"
  steps:
    - name: "Run Checkout by GitHub Actions"
      uses: letsrockthefuture/reusable-workflows/templates/checkout@main

    - name: "Run gosec by Secure Go"
      uses: securego/gosec@master
      with:
        args: "-no-fail -fmt sarif -out results.sarif ./..."

    - name: "Upload SARIF results to code scanning"
      uses: letsrockthefuture/reusable-workflows/templates/codeql/upload-sarif@main
      with:
        sarif_file: results.sarif
