name: "Set up AWS"
description: "Setting up AWS with credentials."

author: "letsrockthefuture"

inputs:
  aws_region:
    description: "The region to authenticate to."
    type: string
    default: "us-east-1"
    required: true

  # aws_access_key_id:
  #   description: "The AWS_ACCESS_KEY_ID environment."
  #   type: string
  #   required: false

  # aws_secret_access_key:
  #   description: "The AWS_SECRET_ACCESS_KEY environment."
  #   type: string
  #   required: false

  role_to_assume:
    description: "The role to assume and grant access to AWS account."
    type: string
    required: true

  role_session_name:
    description: "The role session name."
    type: string
    required: true

runs:
  using: "composite"
  permissions:
    id-token: "write"
    contents: "read"
  steps:
    - name: "Set up AWS credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws_region }}
        # aws-access-key-id: ${{ inputs.aws_access_key_id }}
        # aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        role-to-assume: ${{ inputs.role_to_assume }}
        role-session-name: ${{ inputs.role_session_name }}
