name: "Checkout by GitHub Actions"
description: "Check the project repository code."

author: "letsrockthefuture"

runs:
  using: "composite"
  steps:
    - name: "Run Checkout by GitHub Actions"
      uses: actions/checkout@v2
