version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: 
      - "dependencies"
    reviewers: 
      - "danielvincenzi"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Sao_Paulo"
