name: "Golang"
# description: "Golang workflow"

on:
  workflow_call:
    inputs:
      language:
        description: "The programming language of the project."
        type: string
        required: true

jobs:
  gosec:
    name: "gosec"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Run gosec by Secure Go"
        uses: letsrockthefuture/reusable-workflows/templates/gosec@main

  codeql:
    name: "CodeQL"
    runs-on: "ubuntu-latest"
    needs:
      - gosec
    steps:
      - name: "Initialize CodeQL by GitHub"
        uses: letsrockthefuture/reusable-workflows/templates/codeql@main
        with:
          language: ${{ inputs.language }}

      - name: "Perform CodeQL analysis"
        uses: letsrockthefuture/reusable-workflows/templates/codeql/analyze@main
